site_name: Table 9022

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips

plugins:
  - search
  - awesome-nav:
      filename: .nav.yml 
      logs: 
        nav_override: warning
        root_title: warning
        root_hide: warning
        no_matches: warning

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption