site_name: Family Recipes (NAME IS WIP)

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips

plugins:
  - search
  - awesome-nav:
      filename: .nav.yml 
      logs: 
        nav_override: warning
        root_title: warning
        root_hide: warning
        no_matches: warning
